default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV['WC_DATABASE_POOL'] %> #50
  username: <%= ENV['WC_DATABASE_USER_NAME'] %>
  password: <%= ENV['WC_DATABASE_PASSWORD'] %>
  socket: <%= ENV['MYSQL_SOCKET'] %>
  host: <%= ENV['WC_HOST'] %>

development:
  <<: *default
  database: <%= ENV['WC_DATABASE'] %>

test:
  <<: *default
  database: <%= ENV['WC_DATABASE'] %>

production:
  <<: *default
  database: <%= ENV['WC_DATABASE'] %>
